import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPasswordResetAndReceipt1777981349637 implements MigrationInterface {
    name = 'AddPasswordResetAndReceipt1777981349637'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_expenses_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_recurring_start"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sponsored_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_report_period"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_report_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_trend_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_trend_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_merchant_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_merchant_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cashback_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cashback_merchant_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cashback_status"`);
        await queryRunner.query(`CREATE TABLE "rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "category" character varying(50) NOT NULL, "pointsCost" integer NOT NULL, "affiliateLink" text, "merchantName" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "redemptionCount" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d947441a48debeb9b7366f8b8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_achievements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "achievementType" character varying(100) NOT NULL, "description" text, "completed" boolean NOT NULL DEFAULT false, "progress" integer NOT NULL DEFAULT '0', "target" integer NOT NULL DEFAULT '100', "points" integer NOT NULL DEFAULT '0', "relatedEntityId" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d94aba7e9ed55365f68b5e77fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "referrals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referrer_id" uuid NOT NULL, "referred_id" uuid, "referralCode" character varying(50) NOT NULL, "used" boolean NOT NULL DEFAULT false, "usedAt" TIMESTAMP, "pointsEarned" integer NOT NULL DEFAULT '0', "cashbackEarned" numeric(10,2) NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_13a1bad9eef9e5cfa4b61765261" UNIQUE ("referralCode"), CONSTRAINT "PK_ea9980e34f738b6252817326c08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_referrer_id" ON "referrals" ("referrer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_referral_code" ON "referrals" ("referralCode") `);
        await queryRunner.query(`ALTER TABLE "salary_profiles" DROP COLUMN "quincenaDay"`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" DROP COLUMN "last_generated_at"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "advertiser_id"`);
        await queryRunner.query(`ALTER TABLE "data_reports" DROP COLUMN "insights_json"`);
        await queryRunner.query(`ALTER TABLE "data_reports" DROP COLUMN "buyer_id"`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" DROP COLUMN "average_spending"`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" DROP COLUMN "transaction_count"`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" DROP COLUMN "growth_rate"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "receiptUrl" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "resetPasswordToken" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "resetPasswordExpires" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ADD "startDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ADD "endDate" date`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ADD "lastGeneratedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "advertiserId" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "startDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "endDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "data_reports" ADD "insightsJson" json NOT NULL`);
        await queryRunner.query(`ALTER TABLE "data_reports" ADD "buyerId" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" ADD "averageSpending" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" ADD "transactionCount" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" ADD "growthRate" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD "merchantId" uuid`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD "expenseId" uuid`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "color" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "affiliateLink" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "isRecurringGenerated" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "unlockedAchievements"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "unlockedAchievements" text NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "data_reports" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "data_reports" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "data_reports" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "merchant_affiliates" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "merchant_affiliates" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP COLUMN "merchant_id"`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD "merchant_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP COLUMN "expense_id"`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD "expense_id" character varying`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_user_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_recurring_start" ON "recurring_expenses" ("startDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_c68c6efdb6f80c685ecdaed7e9" ON "sponsored_content" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ae0ac3cf452e9ecb694cd7cbb" ON "data_reports" ("period") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e856a83382f6a8008a6a2970d" ON "consumer_trends" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_21b4cae39d9c849d10c1eee05c" ON "consumer_trends" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_6daf434fd071d00e1fdb8bfcfa" ON "merchant_affiliates" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_21b2ee54dc571ff7a53cd465d3" ON "merchant_affiliates" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_f73757cd5c0aa2986337abab2c" ON "user_cashback" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_54409d8d6b2d485c5c40a9146e" ON "user_cashback" ("merchant_id") `);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_5d1f4be708e0dfe2afa1a3c376c" FOREIGN KEY ("category_id") REFERENCES "expense_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_achievements" ADD CONSTRAINT "FK_c755e3741cd46fc5ae3ef06592c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_18af9fcaffac6d6d3b28130e149" FOREIGN KEY ("referrer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_507a2818bf5524662b068c2e81c" FOREIGN KEY ("referred_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD CONSTRAINT "FK_432005d071f626623be4e343676" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD CONSTRAINT "FK_6ebb4aa851a8253eefe61ce6103" FOREIGN KEY ("merchantId") REFERENCES "merchant_affiliates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD CONSTRAINT "FK_42547c0ae5978b15ed88ec7ebfb" FOREIGN KEY ("expenseId") REFERENCES "expenses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP CONSTRAINT "FK_42547c0ae5978b15ed88ec7ebfb"`);
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP CONSTRAINT "FK_6ebb4aa851a8253eefe61ce6103"`);
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP CONSTRAINT "FK_432005d071f626623be4e343676"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_507a2818bf5524662b068c2e81c"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_18af9fcaffac6d6d3b28130e149"`);
        await queryRunner.query(`ALTER TABLE "user_achievements" DROP CONSTRAINT "FK_c755e3741cd46fc5ae3ef06592c"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_5d1f4be708e0dfe2afa1a3c376c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54409d8d6b2d485c5c40a9146e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f73757cd5c0aa2986337abab2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21b2ee54dc571ff7a53cd465d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6daf434fd071d00e1fdb8bfcfa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21b4cae39d9c849d10c1eee05c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e856a83382f6a8008a6a2970d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ae0ac3cf452e9ecb694cd7cbb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c68c6efdb6f80c685ecdaed7e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_recurring_start"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_email"`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP COLUMN "expense_id"`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD "expense_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP COLUMN "merchant_id"`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD "merchant_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "user_cashback" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "merchant_affiliates" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "merchant_affiliates" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "data_reports" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "data_reports" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "data_reports" ADD "status" character varying(50) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "unlockedAchievements"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "unlockedAchievements" text array DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "isRecurringGenerated" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "affiliateLink" SET DEFAULT NULL`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "color" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expense_categories" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP COLUMN "expenseId"`);
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP COLUMN "merchantId"`);
        await queryRunner.query(`ALTER TABLE "user_cashback" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" DROP COLUMN "growthRate"`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" DROP COLUMN "transactionCount"`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" DROP COLUMN "averageSpending"`);
        await queryRunner.query(`ALTER TABLE "data_reports" DROP COLUMN "buyerId"`);
        await queryRunner.query(`ALTER TABLE "data_reports" DROP COLUMN "insightsJson"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" DROP COLUMN "advertiserId"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" DROP COLUMN "lastGeneratedAt"`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" DROP COLUMN "endDate"`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" DROP COLUMN "startDate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "resetPasswordExpires"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "resetPasswordToken"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "receiptUrl"`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" ADD "growth_rate" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" ADD "transaction_count" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consumer_trends" ADD "average_spending" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "data_reports" ADD "buyer_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "data_reports" ADD "insights_json" json NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "advertiser_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "end_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sponsored_content" ADD "start_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ADD "last_generated_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ADD "end_date" date`);
        await queryRunner.query(`ALTER TABLE "recurring_expenses" ADD "start_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salary_profiles" ADD "quincenaDay" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_referral_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_referrer_id"`);
        await queryRunner.query(`DROP TABLE "referrals"`);
        await queryRunner.query(`DROP TABLE "user_achievements"`);
        await queryRunner.query(`DROP TABLE "rewards"`);
        await queryRunner.query(`CREATE INDEX "IDX_cashback_status" ON "user_cashback" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_cashback_merchant_id" ON "user_cashback" ("merchant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cashback_user_id" ON "user_cashback" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_merchant_category" ON "merchant_affiliates" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_merchant_name" ON "merchant_affiliates" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_trend_date" ON "consumer_trends" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_trend_category" ON "consumer_trends" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_report_status" ON "data_reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_report_period" ON "data_reports" ("period") `);
        await queryRunner.query(`CREATE INDEX "IDX_sponsored_category" ON "sponsored_content" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_recurring_start" ON "recurring_expenses" ("start_date") `);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_expenses_category_id" FOREIGN KEY ("category_id") REFERENCES "expense_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
